# -*- coding: utf-8 -*-
"""PF_Lab_ Project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSq9MruTOzEcCzdYuwWvvDCWaW01Mfel
"""

# Finding inverse of a 2x2 matrix

import math
#creating a matrix and taking inputs
rows=int(input("Enter Rows:"))
columns=int(input("Enter Columns:"))
list2=[]
for i in range(rows):
  list1=[]
  for j in range(columns):
    values=int(input("Enter Values:"))
    list1.append(values)
  list2.append(list1)  
print("Matrix is ",list2)   

#taking determinant
determinant=0
determinant=(list2[0][0]*list2[1][1])-(list2[0][1]*list2[1][0])
print("Determinant is ",determinant)

#taking adjoint
side=list2[0][0]
list2[0][0]=list2[1][1]
list2[1][1]=side

list2[0][1]=(list2[0][1]*-1)
list2[1][0]=(list2[1][0]*-1)
print("Adjoint of matrix is ",list2)

#taking inverse
inverse=[[list2[0][0]/determinant, list2[0][1]/determinant],
                [list2[1][0]/determinant, list2[1][1]/determinant]]
print("The inverse of the matrix is ",inverse )

#finding identity matrix
matrix1=[(inverse[0][0]*list2[0][0])+(inverse[0][1]*list2[1][0])]
matrix1=[(inverse[0][0]*list2[0][0])+(inverse[0][1]*list2[1][0])]
matrix2=[(inverse[0][0]*list2[0][1])+(inverse[0][1]*list2[1][1])]
matrix3=[(inverse[1][0]*list2[0][0])+(inverse[1][1]*list2[1][0])]
matrix4=[(inverse[1][0]*list2[0][1])+(inverse[1][1]*list2[1][1])]
identity=matrix1+matrix2+matrix3+matrix4
print("If we multiply the matrix with its inverse, it results in ",identity,"which is an identity matrix")
